---
- name: installing os centric piece first
  include: "os_family/{{ ansible_os_family }}.yml"

- name: Check if Fisher is already installed
  stat:
    path: "{{ user.home }}/.config/fish/functions/fisher.fish"
  register: fisher_file

- name: Install Fisher
  become: yes
  become_user: "{{ user.name }}"
  shell: "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
  args:
    executable: /usr/bin/fish  # Use /bin/fish for Fish shell-specific commands
  when: not fisher_file.stat.exists

- name: Get the list of installed Fisher plugins
  become: yes
  become_user: "{{ user.name }}"
  shell: "fisher list"
  args:
    executable: /usr/bin/fish  # Use /bin/fish for Fish shell-specific commands
  register: installed_plugins

- name: Install missing plugins
  become: yes
  become_user: "{{ user.name }}"
  shell: "fisher install {{ item }}"
  args:
    executable: /usr/bin/fish  # Use /bin/fish for Fish shell-specific commands
  loop: "{{ fisher_plugins }}"
  when: "'{{ item }}' not in installed_plugins.stdout_lines"

- name: Remove plugins not in the desired list
  become: yes
  become_user: "{{ user.name }}"
  shell: "fisher remove {{ item }}"
  args:
    executable: /usr/bin/fish  # Use /bin/fish for Fish shell-specific commands
  loop: "{{ installed_plugins.stdout_lines | difference(fisher_plugins) }}"
  when: installed_plugins.stdout_lines | difference(fisher_plugins) | length > 0

- name: change the shell to fish
  user:
    name="{{ user.name }}"
    shell=/usr/bin/fish
