---
- name: installing os centric piece first
  include: "os_family/{{ ansible_os_family }}.yml"

- name: Install Fisher
  shell: "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
  args:
    executable: /bin/fish  # Use /bin/fish for Fish shell-specific commands

- name: change the shell to fish
  user:
    name="{{ user.name }}"
    shell=/usr/bin/fish
