
---
- name: Provision Python development laptop
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Python package manager (pip)
      apt:
        name: python3-pip
        state: present

    - name: Install useful Python packages
      apt:
        name: "{{ item }}"
      with_items:
        - python3-virtualenv
        - pyton3-ipython

    - name: Install Git
      apt:
        name: git
        state: present

