
---
- name: Provision Python development laptop
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Python package manager (pip)
      apt:
        name: python3-pip
        state: present

    - name: Install useful Python packages system wide
      apt:
        name: "{{ item }}"
      with_items:
        - python3-virtualenv
        - python3-ipython
        - python3-poetry
        - black
        - pipx

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Add Fish PPA
      apt_repository:
        repo: 'ppa:fish-shell/release-3'
        state: present
    
    - name: Install Fish Shell
      apt:
        name: fish
        state: present
