
---
- name: Provision Python development laptop
  hosts: localhost
  become: yes
  become_user: nick
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Python package manager (pip)
      apt:
        name: python3-pip
        state: present

    - name: Install useful Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - neovim
        - virtualenv
        - ipython

    - name: Install Git
      apt:
        name: git
        state: present

