
---
- name: Provision Python development laptop
  hosts: localhost
  become: yes
  vars:
    user:
      name: "{{ user_name }}"
      home: "{{ user_home }}"
    fisher_plugins: 
      - 'jorgebucaran/autopair.fish'
      - 'PatrickF1/fzf.fish'
      - 'jorgebucaran/nvm.fish'
      - 'jorgebucaran/fisher'
    node_versions:
      - v21.1.0
    nerdfonts_users: [nick]
    nerdfonts_fonts: 
      - fontname: 'AnonymousPro'
      - fontname: 'Arimo'
      - fontname: 'BitstreamVeraSansMono'
      - fontname: 'Cousine'
      - fontname: 'DejaVuSansMono'
      - fontname: 'Go-Mono'
      - fontname: 'FiraCode'
      - fontname: 'Gohu'
      - fontname: 'Inconsolata'
      - fontname: 'Hack'
      - fontname: 'Monoid'
      - fontname: 'Mononoki'
      - fontname: 'ProFont'
      - fontname: 'ProggyClean'
      - fontname: 'RobotoMono'
      - fontname: 'SourceCodePro'
      - fontname: 'SpaceMono'
      - fontname: 'Terminus'
      - fontname: 'UbuntuMono'
      - fontname: 'Ubuntu'
  roles:
    - common
    - fish
    - nvm
    - lazyvim

  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"

    - name: Get Ubuntu Version
      command: lsb_release -r -s
      register: ubuntu_version
      changed_when: false

    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Run argcomplete registration command for pipx
      command: register-python-argcomplete --shell fish pipx >~/.config/fish/completions/pipx.fish
      args:
        creates: "~/.config/fish/completions/pipx.fish"

    - name: Copy Fish aliases template
      template:
        src: "templates/aliases_fish.j2"
        dest: "{{ user_home }}/.config/fish/aliases.fish"
      become: no  # Run as the current user, not as root

    - name: Add fish alises to fish config
      ansible.builtin.lineinfile:
        path: "{{ user_home}}/.config/fish/config.fish"
        line: "source ~/.config/fish/aliases.fish"
        state: present

    - name: Install Starship
      include_tasks: starship.yml
    
    - name: Install nerdfonts
      include_role:
        name: hurricanehrndz.nerdfonts
