
---
- name: Provision Python development laptop
  hosts: localhost
  become: yes
  vars:
    user:
      name: "{{ user_name }}"
      home: "{{ user_home }}"
    fisher_plugins: 
      - 'jorgebucaran/autopair.fish'
      - 'PatrickF1/fzf.fish'
      - 'jorgebucaran/nvm.fish'
      - 'jorgebucaran/fisher'
      - 'evanlucas/fish-kubectl-completions'
    node_versions:
      - v21.1.0
    nerdfonts_users: [nick]
    nerdfonts_fonts: 
      - fontname: 'AnonymousPro'
      - fontname: 'Arimo'
      - fontname: 'BitstreamVeraSansMono'
      - fontname: 'Cousine'
      - fontname: 'DejaVuSansMono'
      - fontname: 'Go-Mono'
      - fontname: 'FiraCode'
      - fontname: 'Gohu'
      - fontname: 'Inconsolata'
      - fontname: 'Hack'
      - fontname: 'Monoid'
      - fontname: 'Mononoki'
      - fontname: 'ProFont'
      - fontname: 'ProggyClean'
      - fontname: 'RobotoMono'
      - fontname: 'SourceCodePro'
      - fontname: 'SpaceMono'
      - fontname: 'Terminus'
      - fontname: 'UbuntuMono'
      - fontname: 'Ubuntu'
  roles:
    - common
    - fish
    - nvm
    - lazyvim
    - kubectl

  tasks:
    - name: Check if wsl.exe is on the PATH
      command: "which wsl.exe"  # This will check if wsl.exe is on the PATH
      register: wsl_check
      ignore_errors: yes  # Ignore errors, as 'which' command will return an error if not found

    - name: Set a fact to determine if the host is WSL
      set_fact:
        is_wsl: "{{ wsl_check.rc == 0 }}"
      when: wsl_check is succeeded

    - name: Get Ubuntu Version
      command: lsb_release -r -s
      register: ubuntu_version
      changed_when: false

    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Run argcomplete registration command for pipx
      command: register-python-argcomplete --shell fish pipx >~/.config/fish/completions/pipx.fish
      args:
        creates: "~/.config/fish/completions/pipx.fish"

    - name: Copy Fish aliases template
      template:
        src: "templates/aliases_fish.j2"
        dest: "{{ user_home }}/.config/fish/aliases.fish"
      become: no  # Run as the current user, not as root

    - name: Add fish alises to fish config
      ansible.builtin.lineinfile:
        path: "{{ user_home}}/.config/fish/config.fish"
        line: "source ~/.config/fish/aliases.fish"
        state: present

    - name: Install Starship
      include_tasks: starship.yml
    
    - name: Install nerdfonts
      include_role:
        name: hurricanehrndz.nerdfonts

    - name: Check for the DISPLAY variable
      ansible.builtin.shell: "echo $DISPLAY"
      register: display_output
      ignore_errors: yes

    - name: Install I3 and related deps
      apt:
        pkg: 
          - i3
          - i3-lock
          - albert
          - py3status
          - nitrogen
          - xscreensaver
      when: (display_output.stdout != "") and not is_wsl
