
---
- name: Provision Python development laptop
  hosts: localhost
  become: yes
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"

    - name: Get Ubuntu Version
      command: lsb_release -r -s
      register: ubuntu_version
      changed_when: false

    - name: Add Fish PPA
      apt_repository:
        repo: 'ppa:fish-shell/release-3'
        state: present

    - name: Add NeoVim PPA Unstable
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable -y'
        state: present
      when: ansible_distribution_version == '23.04'
    
    - name: Add NeoVim PPA Stable
      apt_repository:
        repo: 'ppa:neovim-ppa/stable -y'
        state: present
      when: ansible_distribution_version < '23.04'

    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Neovim
      apt:
        name: neovim
        state: present

    - name: Install Python package manager (pip)
      apt:
        name: python3-pip
        state: present

    - name: Install useful Python packages system wide
      apt:
        name: "{{ item }}"
      with_items:
        - python3-virtualenv
        - python3-ipython
        - python3-poetry
        - black
        - pipx

    - name: Install Git
      apt:
        name: git
        state: present

    
    - name: Install Fish Shell
      apt:
        name: fish
        state: present
