---
- name: Ensure Starship executable exists.
  ansible.builtin.stat:
    path: "/usr/local/bin/starship"
  register: starship

- name: Download and install starship
  become: true
  when: not starship.stat.exists
  block:
    - name: Download starship
      command: curl -sS https://starship.rs/install.sh -o install.sh

    - name: Install starship
      command: sh install.sh -y

    - name: Remove starship install file
      ansible.builtin.file:
        path: install.sh
        state: absent

- name: Ensure the .config/fish/config.fish file exists
  become: no
  ansible.builtin.file:
    path: "{{ user_home }}/.config/fish/config.fish"
    state: touch
    mode: 0600
    modification_time: preserve
    access_time: preserve

- name: Fill the .config/fish/config.fish
  become: no
  environment:
    HOME: "/home/nick"
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.config/fish/config.fish"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - starship.rs"
    block: |
      # Starship.rs
      starship init fish | source

- name: Create the starship.toml
  become: no
  block:
    - name: Ensure the ~/.config/ dir exists
      ansible.builtin.file:
        path: "{{ user_home }}/.config"
        state: directory
        mode: 0750
    - name: Ensure the ~/.config/starship.toml file exists
      ansible.builtin.file:
        path: "{{ user_home }}/.config/starship.toml"
        state: touch
        mode: 0600
        modification_time: preserve
        access_time: preserve

    - name: Fill the starship.toml
      ansible.builtin.blockinfile:
        path: "{{ user_home }}/.config/starship.toml"
        block: |
          command_timeout = 1000

          [directory]
          truncation_length = 3
          truncate_to_repo = true
          truncation_symbol = '…/'

          [aws]
          disabled = false

          [terraform]
          format = 'using 💠($style) '

          [time]
          disabled = false

          [status]
          disabled = false

          [git_branch]  
          symbol = '🌱 '
